"""
_demo_taylor_couette_2d.py — 2D circular Couette flow: rotating inner
cylinder (ROTOR) inside a static outer cylinder (BOUNDARY), laminar.

Validation case for the prescribed rotor motion (predict.comp ROTOR branch,
2026-09-25). The steady laminar azimuthal velocity between the cylinders is

    u_theta(r) = A r + B / r,   A = Omega r_i^2 / (r_i^2 - r_o^2),  B = -A r_o^2

for inner radius r_i rotating at Omega and a static outer wall at r_o. The
wall torque per unit depth is 4 pi mu A r_i^2 ... (for 2D we only compare the
velocity profile; the torque check is done on the 3D tank case).

Geometry (metres): r_i = 0.05, r_o = 0.10 (gap 0.05), rotor solid from
r = r_i - shell to r_i, wall shell from r_o to r_o + shell. Fluid material
stick_water (nu = 1e-3 m^2/s) so the viscous time gap^2 / nu = 2.5 s is
short. Omega = 2 rad/s -> u_i = 0.1 m/s, Re = u_i gap / nu = 5 (laminar).
c0 = 10 u_i = 1 m/s... too low for the pressure field; use 4 m/s (Ma 0.025).

Usage (repo root):
    python utils/geometry/_demo_taylor_couette_2d.py --dx 0.001
"""

from __future__ import annotations

import argparse
import math
import pathlib
import sys

import numpy as np

_REPO_ROOT = pathlib.Path(__file__).resolve().parents[2]
if str(_REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(_REPO_ROOT))

from utils.geometry import LATTICE_GRID, tile_bounding_box    # noqa: E402

INNER_RADIUS = 0.05
OUTER_RADIUS = 0.10
OMEGA = 2.0                      # rad/s, right-hand about +z (counter-clockwise in x-y)
VISCOSITY = 1.0e-3               # stick_water
SPEED_OF_SOUND = 4.0

CASE_YAML = """\
schema_version: 2

# 2D Taylor-Couette (circular Couette) — rotor validation case.
# GENERATED by utils/geometry/_demo_taylor_couette_2d.py.
#   inner cylinder r_i = {ri} rotates at Omega = {omega} rad/s (ROTOR kind),
#   outer cylinder r_o = {ro} static (BOUNDARY kind), gap {gap} m, dx = {dx}
#   fluid {n_fluid:,} / wall {n_wall:,} / rotor {n_rotor:,}
# Analytic steady profile: u_theta = A r + B / r with
#   A = Omega r_i^2 / (r_i^2 - r_o^2), B = -A r_o^2.

time:
  total: null
  max_steps: null
  output_cadence: null

physics:
  dimension: 2
  h: {h:.6f}
  particle_radius: {radius:.6f}
  lattice: grid
  calibrate_volume: true
  speed_of_sound: {c0}
  power: 7
  cfl: 0.15
  gravity: [0.0, 0.0, 0.0]

numerics:
  use_density_diffusion: true
  delta_coefficient: 0.1
  use_kcg_correction: true
  regularization:
    xi: 0.1
    det_threshold: 1.0e-4
    frobenius_max: 10.0
  use_pst: true
  pst_main: 0.1
  pst_anti: 0.0005
  defrag_enabled: true
  defrag_cadence: 1000
  use_prefix_sum_defrag: false

capacities:
  pool_size: {pool_size}
  max_per_voxel: 96
  max_incoming: 16
  workgroup: 128

material_library: materials.yaml

rotor:
  axis: [0.0, 0.0, 1.0]
  pivot: [0.0, 0.0, 0.0]
  ramp_time: 0.1

geometry:
  frame: frame.obj
  particles:
    - {{file: fluid.obj, material: couette_fluid}}
    - {{file: wall.obj,  material: couette_wall}}
    - {{file: rotor.obj, material: couette_rotor}}
"""

MATERIALS_YAML = """\
schema_version: 1

couette_fluid:
  kind: fluid
  rest_density: 1000.0
  viscosity: {nu}

couette_wall:
  kind: boundary
  rest_density: 1000.0
  viscosity: {nu}

couette_rotor:
  kind: rotor
  rest_density: 1000.0
  viscosity: {nu}
  rotor_angular_velocity: {omega}
"""


def write_obj(path, points_2d):
    points_3d = np.column_stack([points_2d, np.zeros(points_2d.shape[0])])
    np.savetxt(path, points_3d, fmt="v %.6f %.6f %.6f",
               header=f"# {points_2d.shape[0]} particles", comments="")


def write_frame_obj(path, half, z_half):
    vertices = np.array([
        [-half, -half, -z_half], [-half, half, -z_half], [half, -half, -z_half], [half, half, -z_half],
        [-half, -half, z_half], [-half, half, z_half], [half, -half, z_half], [half, half, z_half]])
    faces = [(1, 2, 4), (1, 4, 3), (5, 7, 8), (5, 8, 6), (1, 5, 6), (1, 6, 2),
             (3, 4, 8), (3, 8, 7), (1, 3, 7), (1, 7, 5), (2, 6, 8), (2, 8, 4)]
    with open(path, "w") as handle:
        handle.write("# couette frame bbox\n")
        for v in vertices:
            handle.write(f"v {v[0]:.6f} {v[1]:.6f} {v[2]:.6f}\n")
        for f in faces:
            handle.write(f"f {f[0]} {f[1]} {f[2]}\n")


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--dx", type=float, default=0.001)
    parser.add_argument("--hdx", type=int, default=5)
    parser.add_argument("--out", default="cases/taylor_couette_2d")
    args = parser.parse_args()
    dx = args.dx
    h = args.hdx * dx
    shell = args.hdx * dx
    outer = OUTER_RADIUS + shell
    sites = tile_bounding_box([-outer - 0.5 * dx, -outer - 0.5 * dx], [outer + 0.5 * dx, outer + 0.5 * dx],
                              dx, LATTICE_GRID, 2)
    r = np.hypot(sites[:, 0], sites[:, 1])
    is_fluid = (r > INNER_RADIUS + 0.5 * dx) & (r < OUTER_RADIUS - 0.5 * dx)
    is_rotor = (r <= INNER_RADIUS + 0.5 * dx) & (r > INNER_RADIUS - shell)
    is_wall = (r >= OUTER_RADIUS - 0.5 * dx) & (r < outer)
    fluid, wall, rotor = sites[is_fluid], sites[is_wall], sites[is_rotor]
    total = len(fluid) + len(wall) + len(rotor)
    pool = int(math.ceil(total * 1.15 / 128) * 128)
    print(f"dx={dx} h={h} fluid={len(fluid):,} wall={len(wall):,} rotor={len(rotor):,} pool={pool:,}")
    print(f"u_inner = {OMEGA * INNER_RADIUS:.3f} m/s, Re = {OMEGA * INNER_RADIUS * (OUTER_RADIUS - INNER_RADIUS) / VISCOSITY:.1f}, "
          f"viscous time gap^2/nu = {(OUTER_RADIUS - INNER_RADIUS) ** 2 / VISCOSITY:.2f} s, dt = {0.15 * h / SPEED_OF_SOUND:.3e} s")
    out = _REPO_ROOT / args.out
    out.mkdir(parents=True, exist_ok=True)
    write_obj(out / "fluid.obj", fluid)
    write_obj(out / "wall.obj", wall)
    write_obj(out / "rotor.obj", rotor)
    write_frame_obj(out / "frame.obj", outer + 0.6 * dx, 0.5 * dx)
    (out / "case.yaml").write_text(CASE_YAML.format(
        ri=INNER_RADIUS, ro=OUTER_RADIUS, omega=OMEGA, gap=OUTER_RADIUS - INNER_RADIUS, dx=dx,
        n_fluid=len(fluid), n_wall=len(wall), n_rotor=len(rotor), h=h, radius=0.5 * dx,
        c0=SPEED_OF_SOUND, pool_size=pool), encoding="utf-8")
    (out / "materials.yaml").write_text(MATERIALS_YAML.format(nu=VISCOSITY, omega=OMEGA), encoding="utf-8")
    print(f"wrote case -> {out}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
