"""
_demo_cavity_case.py — build a lid-driven-cavity case structure from the tool.

A DEMO that composes the generic geometry tool into a specific case with the same
4-part split as cases/lid_driven_cavity_2d: it does NOT live in the core library
(the library stays case-agnostic). Emits, into the output case dir:

  frame.obj     — bounding-box cube (the loader derives the voxel grid from it)
  domain.obj    — fluid interior  (material stick_water)
  wall.obj      — static U-shaped wall: bottom + both sides + top-side corners (stick_wall)
  wall_top.obj  — moving lid: top band over the fluid width (stick_lid)
  case.yaml     — physics / numerics / capacities, referencing the four .obj

Layout (matches cases/lid_driven_cavity_2d): fluid box [-0.5,0.5]^2 (1 m) on a grid
lattice, surrounded by a BORDER_LAYERS-thick frame; the top band over the fluid width
is the lid, the rest of the frame is wall. h/dx = 5.

    .venv/Scripts/python.exe utils/geometry/_demo_cavity_case.py            # ~6M fluid
    .venv/Scripts/python.exe utils/geometry/_demo_cavity_case.py --half 500 --out cases/..._1m
"""

from __future__ import annotations

import argparse
import math
import pathlib
import sys

import numpy as np

_REPO_ROOT = pathlib.Path(__file__).resolve().parents[2]
if str(_REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(_REPO_ROOT))

from utils.geometry import LATTICE_GRID, tile_bounding_box     # noqa: E402

FLUID_HALF_EXTENT = 0.5            # fluid box [-0.5, 0.5]^2 = 1 m cavity (as in the existing case)


def write_obj(path, points_2d):
    points_3d = np.column_stack([points_2d, np.zeros(points_2d.shape[0])])
    np.savetxt(path, points_3d, fmt="v %.6f %.6f %.6f",
               header=f"# {points_2d.shape[0]} particles", comments="")


def write_preview(path, domain, wall, lid, dx, frame_half_x, frame_half_y, fluid_half_x, fluid_half_y):
    import matplotlib
    matplotlib.use("Agg")
    import matplotlib.pyplot as plt
    figure, axes = plt.subplots(1, 3, figsize=(18, 6))
    sample = np.linspace(0, domain.shape[0] - 1, min(40_000, domain.shape[0])).astype(int)
    axes[0].scatter(domain[sample, 0], domain[sample, 1], s=0.4, c="tab:blue", label="domain/fluid")
    axes[0].scatter(wall[:, 0], wall[:, 1], s=0.4, c="tab:green", label="wall")
    axes[0].scatter(lid[:, 0], lid[:, 1], s=0.4, c="tab:red", label="wall_top/lid")
    axes[0].add_patch(plt.Rectangle((-frame_half_x, -frame_half_y), 2 * frame_half_x, 2 * frame_half_y,
                                    fill=False, ec="k", lw=1.0))
    axes[0].set_title(f"fluid {domain.shape[0]:,} / wall {wall.shape[0]:,} / lid {lid.shape[0]:,}")
    axes[0].set_aspect("equal"); axes[0].legend(markerscale=12, loc="center", fontsize=8)

    def zoom(axis, x_center, y_center, title):
        window = 18 * dx
        for cloud, color in ((domain, "tab:blue"), (wall, "tab:green"), (lid, "tab:red")):
            mask = (np.abs(cloud[:, 0] - x_center) < window) & (np.abs(cloud[:, 1] - y_center) < window)
            axis.scatter(cloud[mask, 0], cloud[mask, 1], s=12, c=color)
        axis.set_title(title); axis.set_aspect("equal")
    zoom(axes[1], -fluid_half_x, fluid_half_y, "top-LEFT corner (wall meets lid)")
    zoom(axes[2], 0.0, fluid_half_y, "top-CENTER (lid over fluid)")
    figure.tight_layout(); figure.savefig(path, dpi=105)
    plt.close(figure)


def write_frame_obj(path, half_extent_x, half_extent_y, z_half):
    # 8-vertex box spanning the grid bounding box (+12 triangles); loader reads the verts' bbox.
    hx, hy, z = half_extent_x, half_extent_y, z_half
    vertices = np.array([
        [-hx, -hy, -z], [-hx, hy, -z], [hx, -hy, -z], [hx, hy, -z],
        [-hx, -hy,  z], [-hx, hy,  z], [hx, -hy,  z], [hx, hy,  z]])
    faces = [(1, 2, 4), (1, 4, 3), (5, 7, 8), (5, 8, 6), (1, 5, 6), (1, 6, 2),
             (3, 4, 8), (3, 8, 7), (1, 3, 7), (1, 7, 5), (2, 6, 8), (2, 8, 4)]
    with open(path, "w") as handle:
        handle.write("# cavity frame bbox\n")
        for vertex in vertices:
            handle.write(f"v {vertex[0]:.6f} {vertex[1]:.6f} {vertex[2]:.6f}\n")
        for face in faces:
            handle.write(f"f {face[0]} {face[1]} {face[2]}\n")


CASE_YAML = """\
schema_version: 2

# 2D lid-driven cavity — {fluid_millions:.1f}M-particle case.
# GENERATED by utils/geometry/_demo_cavity_case.py — same 4-part split as
# cases/lid_driven_cavity_2d:
#   frame    = bounding box of the {size_x_m:.1f} m x {size_y_m:.1f} m cavity
#   domain   = {n_fluid:,} fluid particles filling the cavity interior
#   wall     = {n_wall:,} static U-shaped wall (bottom + two sides + top corners), {border} layers
#   wall_top = {n_lid:,} lid particles (top, {lid} layers); stick_lid has initial_velocity=[1,0,0]
# h = {h:.6f}, dx = {dx:.6f} -> h/dx = 5.

time:
  total: null
  max_steps: null
  output_cadence: null

physics:
  dimension: 2
  h: {h:.6f}
  particle_radius: {particle_radius:.6f}
  lattice: grid
  calibrate_volume: true
  speed_of_sound: 100.0
  power: 7
  cfl: 0.15
  gravity: [0.0, 0.0, 0.0]

numerics:
  use_density_diffusion: true
  delta_coefficient: 0.1
  use_kcg_correction: true
  regularization:
    xi: 0.01      # 0.1 until 2026-09-28: it made (M + xi I)^-1 about 8 % too small (log/2026-09-28_kcg-xi-0p01.md)
    det_threshold: 1.0e-4
    frobenius_max: 10.0
  use_pst: true
  pst_main: 0.1
  pst_anti: 0.0005
  defrag_enabled: true
  defrag_cadence: 1000
  use_prefix_sum_defrag: false

capacities:
  pool_size: {pool_size}
  max_per_voxel: 96
  max_incoming: 16
  workgroup: 128

material_library: ../../materials/standard.yaml

geometry:
  frame: frame.obj
  particles:
    - {{file: domain.obj,   material: stick_water}}
    - {{file: wall.obj,     material: stick_wall}}
    - {{file: wall_top.obj, material: stick_lid}}
"""


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--half", type=int, default=1224,
                        help="fluid half-resolution in y: 0.5/dx (square fluid is "
                             "(2*half+1)^2 particles). 1224 -> ~6.0M, 500 -> ~1.0M, "
                             "1000 -> ~4.0M")
    parser.add_argument("--half-x", type=int, default=None,
                        help="fluid half-resolution in x (default = --half, i.e. square). "
                             "Larger values make a STRETCHED cavity of the same height "
                             "and resolution: fluid x extent = half_x*dx. Used for the "
                             "weak-scaling chain cases (width proportional to slab count, "
                             "so every slab is geometry-identical).")
    parser.add_argument("--border", type=int, default=11, help="wall border layers")
    parser.add_argument("--lid", type=int, default=11, help="lid layers")
    parser.add_argument("--out", default="cases/lid_driven_cavity_2d_6m")
    parser.add_argument("--no-preview", action="store_true", help="skip split_preview.png")
    parser.add_argument("--objs-only", action="store_true",
                        help="write geometry (.obj) only, NEVER touch case.yaml. "
                             "For regenerating gitignored geometry of a TRACKED case "
                             "on a fresh checkout — 2026-09-04 lesson: overwriting the "
                             "tracked 1M case.yaml silently changed gamma 1.4->7, "
                             "materials water->stick and c 20->100, creating an "
                             "unvalidated physics combo that ejects particles at the "
                             "lid corners on every platform.")
    args = parser.parse_args()

    half_index_y = args.half
    half_index_x = args.half_x if args.half_x is not None else args.half
    dx = FLUID_HALF_EXTENT / half_index_y
    particle_radius = 0.5 * dx
    smoothing_length = 5.0 * dx
    border, lid = args.border, args.lid

    # Integer-indexed lattice so the border is EXACTLY `border` layers on every
    # side (a float region extent 0.5 + border*dx gets clipped off-by-one on some
    # sizes due to rounding). Site (kx, ky) sits at (kx*dx, ky*dx); the fluid box
    # is |kx| <= half_index_x, |ky| <= half_index_y, surrounded by `border`
    # index-rings. dx derives from the Y half so stretching in x keeps the
    # resolution and cavity height fixed (1 m).
    half_total_x = half_index_x + border
    half_total_y = half_index_y + border
    index_x, index_y = np.meshgrid(
        np.arange(-half_total_x, half_total_x + 1),
        np.arange(-half_total_y, half_total_y + 1),
        indexing="ij")
    index_x, index_y = index_x.ravel(), index_y.ravel()
    sites = np.column_stack([index_x * dx, index_y * dx])
    in_fluid = (np.abs(index_x) <= half_index_x) & (np.abs(index_y) <= half_index_y)
    is_lid = (index_y > half_index_y) & (np.abs(index_x) <= half_index_x)
    is_wall = (~in_fluid) & (~is_lid)

    domain = sites[in_fluid]
    lid_points = sites[is_lid]
    wall = sites[is_wall]
    n_fluid, n_wall, n_lid = domain.shape[0], wall.shape[0], lid_points.shape[0]
    total = n_fluid + n_wall + n_lid
    pool_size = int(math.ceil(total * 1.15 / 128) * 128)

    fluid_half_x = half_index_x * dx
    fluid_half_y = half_index_y * dx
    out_dir = _REPO_ROOT / args.out
    out_dir.mkdir(parents=True, exist_ok=True)
    print(f"dx={dx:.6e}  h={smoothing_length:.6e}  "
          f"fluid box [-{fluid_half_x:.3f},{fluid_half_x:.3f}] x [-{fluid_half_y:.3f},{fluid_half_y:.3f}]")
    print(f"domain(fluid)={n_fluid:,}  wall={n_wall:,}  wall_top(lid)={n_lid:,}  total={total:,}")
    print(f"pool_size={pool_size:,}  -> {out_dir}")

    write_obj(out_dir / "domain.obj", domain)
    write_obj(out_dir / "wall.obj", wall)
    write_obj(out_dir / "wall_top.obj", lid_points)
    frame_half_x = half_total_x * dx + 0.6 * dx
    frame_half_y = half_total_y * dx + 0.6 * dx
    write_frame_obj(out_dir / "frame.obj", frame_half_x, frame_half_y, particle_radius)
    if args.objs_only:
        print("wrote frame.obj domain.obj wall.obj wall_top.obj "
              "(--objs-only: case.yaml untouched)")
        if not args.no_preview:
            write_preview(out_dir / "split_preview.png", domain, wall, lid_points, dx,
                          frame_half_x, frame_half_y, fluid_half_x, fluid_half_y)
        return 0
    (out_dir / "case.yaml").write_text(CASE_YAML.format(
        fluid_millions=n_fluid / 1e6, n_fluid=n_fluid, n_wall=n_wall, n_lid=n_lid,
        border=border, lid=lid, h=smoothing_length, dx=dx, particle_radius=particle_radius,
        pool_size=pool_size, size_x_m=2 * fluid_half_x, size_y_m=2 * fluid_half_y), encoding="utf-8")
    print("wrote frame.obj domain.obj wall.obj wall_top.obj case.yaml")
    if not args.no_preview:
        write_preview(out_dir / "split_preview.png", domain, wall, lid_points, dx,
                      frame_half_x, frame_half_y, fluid_half_x, fluid_half_y)
        print(f"wrote split_preview.png")
    return 0


if __name__ == "__main__":
    sys.exit(main())
